### ISSUE TITLE
Implement ORM for consistent database code / provide full CRUD API

### ISSUE THREAD

**Issue by aidanh010** [triplestrange/StrangeScout#20]
**What parts of the StrangeScout system does this involve?**
GoScout

**Is your feature request related to a problem? Please describe.**
Currently SQL commands are string literals directly inserted into `main.go`. This is unmaintainable and has already resulted in bugs during testing. Between seasons, to add a new field, to change schema, one must update creator function SQL, update struct, update create API SQL. Once a full CRUD model is added, this alone would be ridiculous, plus the `CREATE IF NOT EXISTS` hack being used currently to enable startup from Compose with an empty database provides no way to upgrade the schema of an existing database, forcing the user to manually attach the volume to a custom container or abandon old data.

**Describe the solution you'd like**
Implement [GORM](https://gorm.io) or similar.

**Describe alternatives you've considered**
We could use the more full-featured Diesel (including CLI and standalone SQL scripts) with a Rust based API server.

**Comment by aidanh010** [comment]
So the current progress is:

* Switching to Echo for easier route configuration, this also would allow us to host the JScout files from within the app and consolidate image size drastically b/c Echo supports automatic lets encrypt.
* Working on GORM implementation. New structs will be `team` and `run` for now. As of right now, `match` and `event` will be handled by sorts.
* Converting all JSON fields to whatever case meets the spec, IIRC its camelCase.
* `match` records will have a "belongs to"-type foreign key relationship with a `team` object. GoScout will create an empty team record if one does not exist.
* API has already been discussed so I'll wait till done to document. We will (mostly) use RESTful design, thus the old `submitMatch` and `submitPit` are deprecated. For now we will support both POST and PUT, as POST will be used when we add versioning to add a new version. Editing can *only* be done via PUT. Attempting to overwrite an existing entry with POST will return a 409 Conflict.
* HEAD and DELETE (as well as GET) methods are to be implemented.

**Comment by PenguinSnail** [comment]
**UPDATE**

- JScout now sanitizes the payload by removing all null or undefined fields - this is important because echo won't take keys with the wrong type even if they're blank, for example a boolean that has not been changed to true or back to false actually submits as a blank string

- A basic echo setup has been developed with proper routes

- A GORM style struct has been made to allow easy editing of the database

- Actually useful comments all throughout the code

I'm hoping to have the backend rewrite completed in a few days, possibly even by next meeting this Friday.
